name: flutter_todos
description: A todos app built with Flutter and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  formz: ^0.4.1
  email_validator: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
